POST http://ec2-3-85-134-149.compute-1.amazonaws.com:8000/login
Content-Type: application/json

{
  "username": "island",
  "password": "1234"
}

###
GET http://localhost:8000/users?id=71km9hl5ul8
Authorization: a0359hgbak6

###
DELETE http://localhost:8000/users?id=71km9hl5ul8
Authorization: zk45dquo8qd

###
GET http://localhost:8000/users?name=island
Authorization: 98syucwugpv

###
PUT http://localhost:8000/users 
Authorization: 98syucwugpv
Content-Type: application/json

{
  "age": 26,
  "email": "huynh@email.com",
  "name": "island",
  "workingPosition": 3
}

###
GET http://localhost:8000/systemInfo
